### ISSUE TITLE
Various stuff to improve

### ISSUE THREAD

**Issue by Rafnuss** [open-geocomputing/OpenEarthEngineLibrary#1]
- [x] change caret design with FA icon https://fontawesome.com/icons/caret-down
- [x] Change the copy button. What is it copying? just the code line? then in the code box
- [x] do not put the argument in a second line in the code exemple
- [x] Maybe add "()" to function title
- [x] change/keep the style of the box of the description
- [ ] revise the "update time"... ugly... 
- [x] Is there anything to add below the how to use ? e.g. "how to cite?", "contact?/ the creator", "used in ...", logo of unil, gaia etc... 
- [x] favicon
- [x] check for logo

**Comment by mgravey** [comment]
- I add the caret, put the argument on the same line, and (...), and update the description box class
- How to cite the lib or each algorithms ? Each algorithm as it own license , we could add a small flag each time, no ?
for the logo, we could add some let me check
- If you have idea for the update time, feel free to change.
- The copy button copy a sequence ready to be use in GEE, it's not exactly the same a code box content

**Comment by Rafnuss** [comment]
Could we make another section exemple and then copy this exemple?
> * The copy button copy a sequence ready to be use in GEE, it's not exactly the same a code box content

**Comment by Rafnuss** [comment]
Ok, let me work on the footer when we have all of these elements
>   for the logo, we could add some let me check
> * If you have idea for the update time, feel free to change.
