### ISSUE TITLE
Savitzky-Golay 

### ISSUE THREAD

**Issue by Hisschao** [open-geocomputing/OpenEarthEngineLibrary#10]
The d_1_ndvi value after sg filtering is very small, what is the reason for this?

**Comment by mgravey** [comment]
can you send a GEE link ?

**Comment by Hisschao** [comment]
https://code.earthengine.google.com/a781f2d3b5242c6fe849602b254d3a21

**Comment by mgravey** [comment]
oh, I see what you mean by very low then.
I fact this is due to the use of "system:time_start" that is the time encoded in millisecond, if you want the derivate in second simply multiply by 1000, same for per days multiply by 8.64e7, etc.

**Comment by Hisschao** [comment]
Thank you for your answer.

**Comment by Hisschao** [comment]
Thank you for your patience with my question. Another question I want to ask is: How do I get the first derivative of the VI time series when I use a filter other than SG (eg harmonic model)?

**Comment by mgravey** [comment]
d_1_ IS the first derivative !!

**Comment by Hisschao** [comment]
Thank you, if SG is not used as a filter, can d_1_ be used as the first derivative?

**Comment by mgravey** [comment]
sure but it's not the derivate of the raw signal, it's the derivate of the filtered signal
