### ISSUE TITLE
SavatskyGolayFilter can't smooth MODIS/061/MOD13A2

### ISSUE THREAD

**Issue by bobilong** [open-geocomputing/OpenEarthEngineLibrary#11]
Hello everyone:
I found that MODIS/061/MOD13A2 can't be smoothed by oeel.ImageCollection.SavatskyGolayFilteron gee, and return null.
And I try to smooth other datasets like MODIS/006/MCD43A4 and example in MODISFiltering, it works.
So I don't understand why?
And how can I smooth MODIS/061/MOD13A2 using oeel.ImageCollection.SavatskyGolayFilteron?
Thank you!

**Comment by mgravey** [comment]
Hi,
can you provide a link with the code that doesn't work?

However, MODIS/061/MOD13A2 is a 16 days composite so you will need to adjust the filter to have enough images based on you degree. Start with like a 60 days window and reduce after.

**Comment by bobilong** [comment]
Thanks for your reply!
The test code is https://code.earthengine.google.com/ac2d220857c4458d4927a1babca02670
I set days as 60, but still get empty image.

**Comment by mgravey** [comment]
here it's
check comments 
https://code.earthengine.google.com/51baa62d4b2b93a5bfe35d7527613162
