### ISSUE TITLE
can't use SavatskyGolayFilter in python

### ISSUE THREAD

**Issue by YANQIN2021** [open-geocomputing/OpenEarthEngineLibrary#12]
Hi,
    I use oeel.ImageCollection.SavatskyGolayFilter in python and define distanceFunction like example, but I get an error like below Fig
![微信图片_20230215085554](https://user-images.githubusercontent.com/114271705/218897651-a40ac3c0-bc2f-45b1-8eda-2f486341c9cf.png)
.
here is my code:
days = 60
millis = ee.Number(days*1000*60*60*24)

maxDiffFilter = ee.Filter.maxDifference(
  difference= millis,
  leftField='system:time_start',
  rightField= 'system:time_start'
)

def distanceFunction(infromedImage, estimationImage):
  return ee.Image.constant(ee.Number(infromedImage.get('system:time_start'))
            .subtract(ee.Number(estimationImage.get('system:time_start'))))

order = 3
smoothed = oeel.ImageCollection.SavatskyGolayFilter(test,maxDiffFilter,distanceFunction)

**Comment by mgravey** [comment]
Hi,
this is an interesting issue, and surprisingly this situation is not in my tests. I know from what is due, I need to think about a proper fix. Is this urgent, I think I don't really time have time before next week.

**Comment by YANQIN2021** [comment]
Thanks for your reply! The question is not urgent, do your busy first. And I also find the oeel.requireJS runime is too long, like Fig. When I use another smooth function in python, it almost use more than 2h, but only 5 min on google earth engine platform.
![微信图片_20230216105012](https://user-images.githubusercontent.com/114271705/219255924-9ae46ebb-6d6a-4e1f-aece-5df30ac9cf17.png)

**Comment by mgravey** [comment]
I don't really know what your smooth function do but I am almost sure that you should use a .get(0), .first() or any similar ee function and not [0]

**Comment by mgravey** [comment]
Fixed and fixed.
I believe I have identified the issue that was causing the computation to run indefinitely. It appears that the deallocation of a particular object was preventing the Python process from terminating.
Fortunately, while addressing this issue, we were able to fix several other related issues as well.

If you encounter any further issues, please don't hesitate to reopen the ticket if related, or simply make a new one.

**Comment by YANQIN2021** [comment]
Thanks for your help!
