### ISSUE TITLE
When using the "Insert function in code editor"(Click on the arrow symbol to the right of the api), there is no response.

### ISSUE THREAD

**Issue by gyzeternal** [open-geocomputing/OpenEarthEngineLibrary#17]
When using the "Insert function in code editor"(Click on the arrow symbol to the right of the api), there is no response.
Error code"Cannot read properties of undefined (reading 'isStatic')"

**Comment by mgravey** [comment]
Thanks for let in me know, I am aware of this issue since few days, i am working on fix.

Best,
Mathieu

**Comment by mgravey** [comment]
A fix was submitted for Chrome and Firefox.
Chrome already accepted it, so you can simply update to the 1.5.1 version for firefox you will need to wait that the review process is finished.

**Comment by gyzeternal** [comment]
Vvvvvvery Thanks! 
Best,
eternal
