### ISSUE TITLE
CalledProcessErro with non-zero exit status 128

### ISSUE THREAD

**Issue by masolele** [open-geocomputing/OpenEarthEngineLibrary#18]
CalledProcessError: Command '['git', 'clone', 'https://github.com/open-geocomputing/OpenEarthEngineLibrary.git', 'OEEL']' returned non-zero exit status 128.

**Comment by mgravey** [comment]
we will lot go far with this !!
what do you try to do ?

**Comment by masolele** [comment]
I am loading a module using Google Earth Engine Python API. This module consists of functions for processing sentinel 1 images in earth engine. I want to run thin in gee python API. In gee I would normally use require('users/robertnag82/usa/:A_sentinel1_preprocessing2').

I tried doing the same in gee python API with
sentpro =oeel.requireJS('users/robertnag82/usa/:A_sentinel1_preprocessing2')

I also tried using https://geemap.org/notebooks/120_javascript/ but keep getting the same error
sentpro = geemap.requireJS('users/robertnag82/usa/:A_sentinel1_preprocessing2')

**Comment by mgravey** [comment]
Hi,
I am not 100% sure, but from my test it's more a [geemap issue](https://github.com/gee-community/geemap/issues)
It look like you repo need to be public such as ou can automatically load it like that.

Personally, I would advise you to copy your js in a file and to import the file with a local path.

I am not sure, because the error I get is different and make much more sense.
Are you on a windows ?
Are you sure to have git installed and in the path ?

**Comment by masolele** [comment]
The repo is public, I have git version 2.25.1.  and I work on a Linux server. I will try copying the js file locally and i hope that will work. 

On the other hand, I get the same error when importing oeel.
from oeel import oeel
 CalledProcessError: Command '['git', 'clone', 'https://github.com/open-geocomputing/OpenEarthEngineLibrary.git', 'OEEL']' returned non-zero exit status 128.

**Comment by masolele** [comment]
![Capture](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/31400779/5a56d0df-a552-43ca-952a-fed409a4b111)

**Comment by mgravey** [comment]
Did you by accident ˋsudo pip install oeelˋ ? I mean with sudo
Maybe an issue happen if the user that run the initialize of oeel do not have write access on the oeel package directory

**Comment by masolele** [comment]
I used pip install oeel

**Comment by mgravey** [comment]
I assume you try to uninstall and reinstall oeel.

The error message is clear "could not create work tree dir 'OEEL': Permission denied "

So for sure it's a write access issue. Now, why? is complicated to know. can you run the initialisation in a sudo python ? else you can go in the oeel package directory and run a the git clone command from there ?

**Comment by masolele** [comment]
I dont have sudo access! let me try your suggestiob of running a the git clone command from the oeel package directory.

**Comment by mgravey** [comment]
did you find a work around ?
