### ISSUE TITLE
weights in SavatskyGolayFilter

### ISSUE THREAD

**Issue by kongdd** [open-geocomputing/OpenEarthEngineLibrary#19]
Points with different quality, should give different weights. 
Any idea and any plan to implement this feature?

Thanks
![image](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/9815742/0b09550b-1b6a-40c4-a9ff-d2532f58f69c)

**Comment by mgravey** [comment]
this is an interesting idea, how do you expect to pass this information ? as an extra band ?

**Comment by kongdd** [comment]
@mgravey and @agathearchidoit, 

Could give some explaination about the parameter `extrapolate_flag`? 
https://github.com/open-geocomputing/OpenEarthEngineLibrary/blob/5f82c48e5dde59c4728e465360c65df28acf037b/ImageCollection/SavatskyGolayFilter#L51-L54

In theory, `extrapolate_flag` should always be zero.
https://code.earthengine.google.com/a1c4e3359e1c4fdc351238c74becfbbc

There are only three conditions: 

1. `t` in the range of `[-nt, nt]`, `extrapolate = 0`;
2. `t` in the range of `[-nt, 0]`, `extrapolate = 0`;
3. `t` in the range of `[0, nt]`, `extrapolate = 0`;

**Comment by kongdd** [comment]
In my R package phenofit, I implemented the weighted SG.

- <https://github.com/eco-hydro/phenofit/blob/master/src/smooth_wSG.cpp#L127> 
- <https://github.com/eco-hydro/phenofit/blob/master/R/smooth_wSG.R>

But it is a little bit complex to translate. I will try whether it is possible.

**Comment by mgravey** [comment]
The extrapolation flag tell you when all conditioning points are on a single side.
Usually it's a sign that it would be very wrong :) But why do you imagine that it should be always at 0 ?, typically the first and last point of a series are not. But it can happen even in the middle of a series if it's to parse compared to the windows.

Based on [Wikipedia](https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter#Weighting_the_data) it doesn't look complicated.

You still didn't answer to my question! how do you expect to pass this information, as a band ? One for each variable ? As a feature for each image ?

**Comment by kongdd** [comment]
- Because the `saveAllJoin` will always include the current image (i.e., dT = 0). Hence, `extrapolate` does not work as expected.

https://github.com/open-geocomputing/OpenEarthEngineLibrary/blob/5f82c48e5dde59c4728e465360c65df28acf037b/ImageCollection/SavatskyGolayFilter#L32

- Yes, qc can be translated into weights, as an additional band pass to SG. I will give an example of gee Whittaker shortly, which implements this feature.

**Comment by mgravey** [comment]
The estimation collection can be very different of the inputCollection, if you work with MODIS, you are probably both at a daily basis, but with Landsat or Sentinel it allow to get estimation on a constant intervals, even if the input is not.

**Comment by mgravey** [comment]
Sorry wrong button
