### ISSUE TITLE
Colab AuthAndInitilize

### ISSUE THREAD

**Issue by giswqs** [open-geocomputing/OpenEarthEngineLibrary#20]
The Colab AuthAndInitilize method seems not working. 

![image](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/5016453/a7b538f2-f9a3-4c29-8363-2fb4a56a3dba)

**Comment by mgravey** [comment]
Interesting,

Does this occur consistently or sporadically?
Is https://code.earthengine.google.com/ set for automatic login, meaning you land directly on the CE page, or is manual login required each time?
Could you specify the version of the Chrome extension you are using?
May I have the complete trace?

**Comment by mgravey** [comment]
any news on this ??

**Comment by giswqs** [comment]
I have been out of town this week. Have not had time to look into this yet.

**Comment by mgravey** [comment]
the feature was remove because alternative are probably simpler and more performant
