### ISSUE TITLE
oeel name 'colab' is not defined

### ISSUE THREAD

**Issue by koala17github** [open-geocomputing/OpenEarthEngineLibrary#22]
Hello , I encountered this problem while using oeel in Colab. How can I solve it?
![Uploading oeel.png…]()

**Comment by koala17github** [comment]
![oeel](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/91057794/6bb53735-e890-49d6-b679-a358b8655d99)

**Comment by mgravey** [comment]
sorry for this, corrected !!
