### ISSUE TITLE
oeel  name'colab' is not defined

### ISSUE THREAD

**Issue by koala17github** [open-geocomputing/OpenEarthEngineLibrary#23]
Hello , I encountered this problem while using oeel in Colab. How can I solve it?
![oeel](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/91057794/d053f7d6-aa7d-406b-8d6f-9a4843caf681)

**Comment by mgravey** [comment]
I did an update of the package and it should be solved with version 9.8.8, simply update the oeel install
`pip install oeel -U`

**Comment by koala17github** [comment]
It can run now, thank you very much

**Comment by mgravey** [comment]
thanks for the report
