### ISSUE TITLE
oeel   No module named 'termios'

### ISSUE THREAD

**Issue by koala17github** [open-geocomputing/OpenEarthEngineLibrary#24]
Hello, I encountered this problem while using oeel in Jupyter Notebook on a Windows system. How can I solve it?
![oeel jupyter notebook](https://github.com/open-geocomputing/OpenEarthEngineLibrary/assets/91057794/395b2c50-4aaa-4d3a-a78e-367788a1a223)

**Comment by mgravey** [comment]
you should apply the last update and it will disappear
