### ISSUE TITLE
oeel.Export.ImageCollection.toDrive error

### ISSUE THREAD

**Issue by xingguangYan** [open-geocomputing/OpenEarthEngineLibrary#4]
hello,mgravey
when i use region Parameters，The following error will be prompted：

Can't convert a computed Geometry to GeoJSON. Use evaluate() instead.

`var table = ee.FeatureCollection("users/bqt2000204051/shanxibianjie").geometry();`
`oeel.Export.ImageCollection.toDrive({
  imageCollection:lansdat.select("B1","B2","B3","B4"),
  folder:"shanxi_landsat_sr_1986_30m_105_Single_Image", 
  **region:table,** 
  scale:30,
  shardSize:16,
  skipEmptyTiles :true,
  maxPixels:1e13, 
  //autoExport:true})

   }) `

my code link:
https://code.earthengine.google.com/5e90c442fd90a0dbb6550932f19256b8

thanks.

**Comment by mgravey** [comment]
This feature is to complicated to maintain and would be remove, use instead "Run All"

**Comment by xingguangYan** [comment]
got you thanks





---Original---
From: "Mathieu ***@***.***&gt;
Date: Sat, Nov 5, 2022 04:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-geocomputing/OpenEarthEngineLibrary] oeel.Export.ImageCollection.toDrive error (Issue #4)




 
This feature is to complicated to maintain and would be remove, use instead "Run All"
