### ISSUE TITLE
CalledProcessError: Command 'npm install @google/earthengine' returned non-zero exit status 4294963248.

### ISSUE THREAD

**Issue by kenansun** [open-geocomputing/OpenEarthEngineLibrary#6]
when i excute import it back a error :
from oeel import oeel
CalledProcessError                        Traceback (most recent call last)
d:\nameSpace\gitPackage\gitSynSpace\geemap\examples\notebooks\120_javascript.ipynb Cell 24 in <cell line: 1>()
----> [1](vscode-notebook-cell:/d%3A/nameSpace/gitPackage/gitSynSpace/geemap/examples/notebooks/120_javascript.ipynb#ch0000023?line=0) from oeel import oeel

File d:\software\develop\Miniconda3\envs\geo\lib\site-packages\oeel\__init__.py:53, in <module>
     50 		open(oeelLibPath+'/initialized', 'a').close()
     51 		print('Initilization of OEEL is finished')
---> 53 initialize()
     55 subprocess.Popen(['git', 'pull'], cwd=oeelLibPath+'/OEEL',stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
     57 class dotdict(dict):

File d:\software\develop\Miniconda3\envs\geo\lib\site-packages\oeel\__init__.py:43, in initialize()
     41 if nodePath:
     42 	if(which('npm')):
---> 43 		subprocess.check_output("npm install @google/earthengine",shell=True)
     44 		subprocess.check_output("npm install zeromq@6.0.0-beta.6",shell=True)
     45 		subprocess.check_output("npm install request",shell=True)

File d:\software\develop\Miniconda3\envs\geo\lib\subprocess.py:424, in check_output(timeout, *popenargs, **kwargs)
    421         empty = b''
    422     kwargs['input'] = empty
--> 424 return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    425            **kwargs).stdout
...
--> 528         raise CalledProcessError(retcode, process.args,
    529                                  output=stdout, stderr=stderr)
    530 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command 'npm install @google/earthengine' returned non-zero exit status 4294963248.

**Comment by kenansun** [comment]
i hava fix this problom ,because i  change the npm cathe file from c:// to npm install file ,  the npm have not the pession of this file , the give all win user permisson  then fixed

**Comment by mgravey** [comment]
Interestingly at the same time I introduced a safety around. 
Great minds think alike
